- name: Demo on Variables
  hosts: all
  vars:
    URL: play.example.com
    URL2: www.google.com
    URL3: www.microsoft.com
  tasks:
    - name: print the first URL
      ansible.builtin.debug:
        msg: {{URL}}

    - name: print the second URL
      ansible.builtin.debug:
        msg: {{URL2}}

    - name: print the third URL
      ansible.builtin.debug:
        msg: {{URL3}}

