- name: Demo on Variables
  hosts: all
  vars:
    URL: play.example.com
    URL2: www.google.com
    URL3: www.microsoft.com
  tasks:
    - name: print the first URL
      ansible.builtin.debug:
        msg: The First URL is {{URL}}



- name: second demo on variables
  hosts: all
  vars_files:
    - vars-sample.yml
  tasks:
    - name: printing the 4th URL
      ansible.builtin.debug:
        msg: the fourth url is the {{ URL4 }}


#### TASK LEVEL VARIABLES
- name: showing examples for task level variables
  hosts: all
  tasks:
    - name: printing the 7th URL
      ansible.builtin.debug:
        msg: "{{ URL7 }}"
      vars:
        URL7: www.vyjayanthimovies.com


