- name: Demo on Variables
  hosts: all
  vars:
    URL: play.example.com
    URL2: www.google.com
    URL3: www.microsoft.com
  tasks:
    - name: print the first URL
      ansible.builtin.debug:
        msg: The First URL is {{URL}}

    - name: print the second URL
      ansible.builtin.debug:
        msg: The Second URL is {{URL2}}

    - name: print the third URL
      ansible.builtin.debug:
        msg: The Third URL is {{URL3}}


- name: second demo on variables
  hosts: all
  vars_files:
    - vars-sample.yml
  tasks:
    - name: printing the 4th URL
      ansible.builtin.debug:
        msg: the fourth url is the {{ URL4 }}

    - name: printing the 5th URL
      ansible.builtin.debug:
        msg: the fourth url is {{ URL5 }}

    - name: printing the 6th URL
      ansible.builtin.debug:
        msg: the fourth url is {{ URL6 }}


